# Generated by Django 5.2 on 2025-04-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictionjob",
            name="sequence",
        ),
        migrations.RemoveField(
            model_name="predictionjob",
            name="solubility_result",
        ),
        migrations.RemoveField(
            model_name="predictionjob",
            name="thermostability_result",
        ),
        migrations.RemoveField(
            model_name="predictionjob",
            name="toxicity_result",
        ),
        migrations.AddField(
            model_name="predictionjob",
            name="results",
            field=models.TextField(
                blank=True,
                help_text="JSON formatted list of prediction results for all sequences",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="predictionjob",
            name="sequence_count",
            field=models.IntegerField(
                default=0, help_text="Number of sequences in this job"
            ),
        ),
        migrations.AlterField(
            model_name="predictionjob",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Optional job name (e.g., filename or user input)",
                max_length=200,
                null=True,
            ),
        ),
    ]
