# Generated by Django 5.1.8 on 2025-04-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0002_remove_predictionjob_sequence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteVisitCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Site Visit Counter",
            },
        ),
    ]
